### ISSUE TITLE
Double-check and modify references to parser and core

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/http-apis.github.io#18]
Now that the parser and core have been moved to their own repository, documentation has to point to the new repos:
* https://github.com/HTTP-APIs/hydra-openapi-parser/issues
* https://github.com/HTTP-APIs/hydra-python-core/issues

**Comment by sukhdeepg** [comment]
@Mec-iS hello! are you referring to [this link](http://www.hydra-cg.com/) as the documentation? If not, please point me to the correct documentation and I'll do the needful changes.

**Comment by de-sh** [comment]
> @Mec-iS hello! are you referring to [this link](http://www.hydra-cg.com/) as the documentation? If not, please point me to the correct documentation and I'll do the needful changes.

Hey @sukhdeepg we use hydraecosystem.org, for documenting our implementation of the Hydra draft.

**Comment by sukhdeepg** [comment]
@de-sh Thanks for the feedback. My only confusion is to on which page to put the links. The place where I though it should go was this 
![Hydra W3C Community Group](https://user-images.githubusercontent.com/28823267/59547178-0f69d980-8f58-11e9-81f2-f31a08322144.png)

**Comment by de-sh** [comment]
@sukhdeepg we don't intend to modify the Hydra-CG docs. Here @Mec-iS is pointing towards making changes in this repo, we used to have these two modules within [hydrus](https://github.com/http-apis/hydrus) that were moved out into their own repos recently. We want to mirror this fact in our docs by changing reference to the old modules showing clearly that they are in their own repos now.

**Comment by sukhdeepg** [comment]
@de-sh thanks for the prompt response. Now as considering the hydraecosystem.org as your doc. I went and searched the doc and found these:
![check1](https://user-images.githubusercontent.com/28823267/59547460-10e9d080-8f5d-11e9-8cbd-d9757fadfe69.png)
![check2](https://user-images.githubusercontent.com/28823267/59547461-12b39400-8f5d-11e9-9ce0-6df25c3fc0a6.png)
I wasn't able to find any mention of hydra-python-core. If I'm still missing something, please do correct me. Thanks for the patience.

**Comment by de-sh** [comment]
It's not only about linking to the correct repo. We intend to write better documentation for the project. Currently the documents here concern mostly the previous iteration of hydrus, we have changed a lot since then. We intend to write documentation in order to reflect those very changes. If you can help, do try re-writing some of the pages after understanding the codebase or the applications of the code. 

As you mention, the parser page is a good option to start with, we need to make sure different components of the suite are not documented, at all. We need better, more well rounded explanations of the same.

**Comment by sukhdeepg** [comment]
@de-sh understood. Thanks. I'll start with that then.

**Comment by Guttz** [comment]
The references were checked and the existing ones modified in https://github.com/HTTP-APIs/http-apis.github.io/pull/52 and https://github.com/HTTP-APIs/http-apis.github.io/pull/53.

What we might need is actually an own page for python core, will open an issue for this.
