### ISSUE TITLE
Add Gitter icon/ribbon to the homepage

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/http-apis.github.io#20]

**Comment by chairmanccc** [comment]
Hi can I take up this issue and resolve it?

**Comment by salman-bhai** [comment]
Hi can I take this up?

**Comment by Mec-iS** [comment]
You don't need to ask. Just propose a Pull Request as defined in the [Github Flow](https://guides.github.com/introduction/flow/)
