### ISSUE TITLE
Parser page found not found

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/http-apis.github.io#21]
The page under https://www.hydraecosystem.org/Parser is returning not found instead of returning the content at https://github.com/HTTP-APIs/http-apis.github.io/blob/master/pages/Parser.md

**Comment by Mec-iS** [comment]
This is weird as the other pages are linked in the very same way (using `Parser.md` as a link) and they work fine.

@xadahiya

**Comment by xadahiya** [comment]
Fixed
