### ISSUE TITLE
Twitter widget size

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/http-apis.github.io#44]
I think the Twitter widget on the main page is too big, compared to the other content on the page. It looks a bit distracting.

It might look more visually pleasing if it was smaller and maybe more to the side rather than centered and huge like it is right now. Something similar to this:

![Screenshot from 2019-05-21 09-26-21](https://user-images.githubusercontent.com/10355740/58067464-fe24eb80-7baa-11e9-949e-8479e16304fd.png)

**Comment by xadahiya** [comment]
I agree! We need a redesign along with a side panel as described in #43

**Comment by de-sh** [comment]
We can do a simple fix for this, resize the iframe to the appropriate size.

**Comment by chrizandr** [comment]
Resolved
