### ISSUE TITLE
Write an article about Hydra usage for OS maps

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/http-apis.github.io#48]
This API publishes OpenStreetMap tiles using Hydra: https://tiles.openplanner.team/planet/14/8411/5485/

It would be good to have a page in the docs or an article explaining this implementation.

In particular check usage at:
```
"hydra:search":{
  "@type":"hydra:IriTemplate",
  "hydra:template":"https://tiles.openplanner.team/planet/14/{x}/{y}",
  "hydra:variableRepresentation":"hydra:BasicRepresentation",
  "hydra:mapping":[{
    "@type":"hydra:IriTemplateMapping",
    "hydra:variable":"x",
    "hydra:property":"tiles:longitudeTile",
    "hydra:required":true
    },{
    "@type":"hydra:IriTemplateMapping",
    "hydra:variable":"y",
    "hydra:property":"tiles:latitudeTile",
    "hydra:required":true}]}}
```

[UPDATE]
We have already a [document page that describes this](https://github.com/HTTP-APIs/http-apis.github.io/blob/master/pages/IriTemplate.md), but we may want to have an article that demos the usage of navigating the API and explains why Hydra is useful for that.

**Comment by de-sh** [comment]
Interested
