### ISSUE TITLE
Mobile view, overflow

### ISSUE THREAD

**Issue by de-sh** [HTTP-APIs/http-apis.github.io#49]
There is a content overflow issue when looking at the website in mobile view.

![Screenshot_20190604-211657_Brave](https://user-images.githubusercontent.com/18750864/58893761-5eb93a00-870e-11e9-8924-e20fd001b670.png)
And
![Screenshot_20190604-211706_Brave](https://user-images.githubusercontent.com/18750864/58893785-68db3880-870e-11e9-9c42-c8abb3961049.png)

Display the same.

**Comment by Guttz** [comment]
Fixed at https://github.com/HTTP-APIs/http-apis.github.io/pull/50.

![image](https://user-images.githubusercontent.com/11739405/58904578-172faf80-8708-11e9-82a4-58435150d494.png)
