### ISSUE TITLE
Additions to Starting-Material.md

### ISSUE THREAD

**Issue by PrajwalM2212** [HTTP-APIs/http-apis.github.io#5]
In the Starting-Material.md, it would be super helpful if **Linked Data** and **JSON-LD** were added before specifications. The https://www.hydra-cg.com/spec/latest/core/  require an understanding of these concepts.

**Comment by PrajwalM2212** [comment]
https://www.w3.org/standards/semanticweb/data for linked data

**Comment by PrajwalM2212** [comment]
https://json-ld.org/spec/latest/json-ld/ for JSON-LD

**Comment by Mec-iS** [comment]
https://github.com/HTTP-APIs/http-apis.github.io/pull/6
