### ISSUE TITLE
Hydra Eco Demo - [Discussion]

### ISSUE THREAD

**Issue by Guttz** [HTTP-APIs/http-apis.github.io#58]
Hello guys,

So I've been trying to architect a straightforward but complete demo that enables people to quickly try Hydra Eco's tools and get the feel of Hydra/Semantics/Linked Data. This is what I came up considering our time frame: 

(Click to expand)
![Group h1](https://user-images.githubusercontent.com/11739405/61073311-88d7d900-a3eb-11e9-9607-b97a4b3c0a65.png)

1. This is the API Graphical representation. It has three already deployed -similar but slightly different- hydrus APIs that the user can select as the target. **The goal is to show how decoupled/constant the Agent can be even with different APIs.**

2. This is where the user can interact. Since we want the user to easily interact without much semantics knowledge, this is a dynamic interface(built according to the apidoc) for the Agent. It has buttons for the critical parts so the user can always send some request and see what happens. The red buttons are the selected ones, and a valid combination will always be selected. **The goal here is for the user to feel that a hypermedia API will give the Agent enough information to automatically structure all kinds of requests possible and create a descriptive environment .**

3. This is where the user can insert data/filter and write more detailed interactions, instead of only fetching the whole collection. Here the user can also use the new search functionalities and query for linked data. For example, he can filter a drone by the battery of it's State DroneState[Battery]. **The goal here is for the user to feel the advantages of Linked data + Hydra**.

Important Obs.:
- This mockup is mostly to discuss functionality. Since I think there's a decent likelihood we use Flask to maintain the whole demo in Python(also up for discussion), it will look different.
- The graph on the left won't be dynamic, at least at first, or else it will take too long. I'm thinking about three different static SVGs.
- Mobile responsiveness won't be an initial concern.

**Comment by xadahiya** [comment]
>  It has three already deployed -similar but slightly different- hydrus APIs that the user can select as the target.

What if the user wants to connect a new hydrus server/ disconnect one? You should think of way to enable that as well.

> This is where the user can interact. Since we want the user to easily interact without much semantics knowledge, this is a dynamic interface(built according to the apidoc) for the Agent. It has buttons for the critical parts so the user can always send some request and see what happens.

Great idea! :thumbsup:

> The red buttons are the selected ones, and a valid combination will always be selected.

Red is not the ideal color for selected items. You should think of some other color like blue

> The graph on the left won't be dynamic, at least at first, or else it will take too long. I'm thinking about three different static SVGs.

The section on the right is fine but I think the left section is very poorly used. A couple of things that can be done - 
- Add an input field to add new hydra servers
- Add a way to remove added servers
- Add a way to issue raw commands to the agent and the output will be displayed in the agent console.(interaction with the agent in console like interface)
- The SVG image you've used isn't explaining much and I think static SVGs won't server any purpose they'll just waste space.
- One thing we can do here is generating the object graph dynamically from the API doc whenever some endpoint/item is selected. This can be done using some JS library like D3.js easily.

**Comment by Guttz** [comment]
> Add a way to issue raw commands to the agent and the output will be displayed in the agent console.(interaction with the agent in console like interface)

I really like this. We can do an input field that is automatically filled on the right side when the user is playing with the console, allowing him to modify the raw command before sending or even writing his own.

> One thing we can do here is generating the object graph dynamically from the API doc whenever some endpoint/item is selected. This can be done using some JS library like D3.js easily

This is definitely the ultimate goal. I would really like to add this in the demo, so it becomes totally generic. I played with d3.js/vis.js/sigma.js and had some problems for it to look intuitive sometimes.  I suggested a SVG for each ApiDoc, for now, to simulate this and fit our time frame while we focus on the dynamic part and the rest of the demo.

> What if the user wants to connect a new hydrus server/ disconnect one? You should think of way to enable that as well. Add an input field to add new hydra servers.

When selecting the server on top, he is disconnecting/connecting to the servers. Adding servers by link(already deployed servers) is a good idea and doable. Enabling the user to upload an ApiDoc and launching a hydrus server is out of the scope for now.

**Comment by Guttz** [comment]
To be honest, for the left part I drew and imagined something more complex at first. Take a look at the left part below:

![Group 9](https://user-images.githubusercontent.com/11739405/61126573-31854780-a483-11e9-9c98-d477f689139b.png)

The ideal would be to show a connected Hydrus Network, where the Agent can issue a command and leverages of linked data of two different hydrus instances. So you can query a Drone that has a problem by its Responsible Technician, for example, which is info from another server. However, we don't have routing in hydrus yet for other servers and some other things that yet makes this really challenging. But in the future, this could be an upgrade for the demo.

**Comment by xadahiya** [comment]
Given the time constraints we have, It would probably be best if we used the existing architecture from last year. @Guttz what you're proposing and what we have [here](https://github.com/HTTP-APIs/hydra-astrodemo/) are quite similar and can be updated according to our needs.
We'll need to - 
- Use the new agent (with sync mechanism)
- Use the latest version of hydrus
- The UI needs a lot of improvement (feel free to get creative in this aspect)
- Add features that you want to implement (as we discussed above)

The end goal is to be able to demonstrate the agent's as well as hydrus's capabilities (along with the sync mechanism we implemented) to people who're new to the semantic web realm.

@Mec-iS @chrizandr @vddesai1871 ^^

**Comment by vddesai1871** [comment]
Just adding on what's listed above, while updating hydrus to its newer version, we'll need to update AstroDemo ApiDoc, to make it compatible with Hydra(as the old Doc is using removed/replaced terms like `statusCodes`, `readonly`, etc.) besides that once `HydraLink` is implemented we can introduce its use in the ApiDoc. I'll explore the project more and I'll try to improve the ApiDoc so it includes major Hydra components.

**Comment by Mec-iS** [comment]
> Use the new agent (with sync mechanism)

This is not really a strict requirement for now

**Comment by Guttz** [comment]
For timing reasons, I agree using the same architecture makes a lot of sense. I investigated the repo to check how much work it would save us as a headstart however I ran into some key points that might lead to a longer development time:

- It uses the "natural language" interface for all requests and if we want to showcase the new agent, the one I'm moving on with, I have to rebuild all the querying part. 

- It focuses on showcasing the parser, which means that all modifications made to the Hydra Spec/core since last years GSoC have to be done to the Parser, so some fixes that were yet to be made in the Parser before we started and all the changes Vishal has made this summer. Overall from my experience with the Parser this should time a while, also for every Spec/Core update this has to be done again so the demo continues to work updated.

- The Astrodemo is now a local-based demo so it has everything in one repo.. What I'm thinking now is a cloud-based demo that will have separate hydrus launched servers, a public deployed ui and a small backend to dynamically deploy agents for the UI to use.

- Then also we have to solve all major updates on our repos for the demo to run, porting doc maker/writer and parser outside of hydrus, then agent updates and hydrus for the current demo to work with our updated repos.

**Comment by Guttz** [comment]
By the way, is there more documentation apart from https://medium.com/openapi-hydra-parser-gsoc2018/astrodemo-build-your-own-spaceship-e4a297131abe to better understand how was it built/should work?

**Comment by vddesai1871** [comment]
>It focuses on showcasing the parser, which means that all modifications made to the Hydra Spec/core since last years GSoC have to be done to the Parser, so some fixes that were yet to be made in the Parser before we started and all the changes Vishal has made this summer. Overall from my experience with the Parser this should time a while, also for every Spec/Core update this has to be done again so the demo continues to work updated.

Repo has both an OpenAPI doc and HydraDoc. For now, we can update HydraDoc in accordance with changes made at Spec/Core and use it directly instead of the openapi doc.

**Comment by Guttz** [comment]
This is a crude architecture of what I have been thinking about the last days:

![Group 17](https://user-images.githubusercontent.com/11739405/62368427-f1096e80-b502-11e9-8102-4b75b326af06.png)

**Comment by xadahiya** [comment]
As discussed on Conf. call, further discussion will be done in project-specific repos. 
Closing this
