### ISSUE TITLE
Create a page that explains the IriTemplate starting from an example

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/http-apis.github.io#7]
Starting from the triples example in https://github.com/HydraCG/Specifications/issues/171

That has been ported in JSON-LD by @vddesai1998  as:
```
{
    "@context": "/serverapi/context.jsonld",
    "@id": "https://tiles.openplanner.team/planet",
    "@type": "Collection",
    "search": {
        "@type": "IriTemplate",
        "template": "https://c.tile.openstreetmap.org/{z}/{x}/{y}.examplejsonld",
        "variableRepresentation": "BasicRepresentation",
        "mapping": [
            {
                "@type": "IriTemplateMapping",
                "variable": "x",
                "property": "tiles:longitudeTile",
                "required": true
            },
              {
                "@type": "IriTemplateMapping",
                "variable": "y",
                "property": "tiles:latitudeTile",
                "required": true
            },
              {
                "@type": "IriTemplateMapping",
                "variable": "z",
                "property": "tiles:zoomTile",
                "required": true
            }
        ]
    }
}
```
Produce a documentation section that explains:
* which problem is solved (uniquely identify a tile on a map by indication of row, height and zoom)
* how the variables in the IRI (`z/x/y`) are mapped to a templates
* what is VariableRepresentation
* ...

**Comment by Mec-iS** [comment]
another example is showed [here](https://github.com/HydraCG/Specifications/issues/161#issue-309433788)

**Comment by pietercolpaert** [comment]
Other examples:
 * The Linked Connections specification for route planning: https://linkedconnections.org/specification/1-0#metadata → this has a property lc:departureTimeQuery: it means it’s going to redirect to a page in an ordered page collection that contains the timestamp given. A production instance for the Belgian railways at https://graph.irail.be/connections/sncb
 * Triple Pattern Fragments specification for graph pattern querying: https://www.hydra-cg.com/spec/latest/triple-pattern-fragments/. A production instance on wikidata: https://query.wikidata.org/bigdata/ldf

And something that may be of interest, but does not use hydra:search is the Tree Ontology: https://github.com/pietercolpaert/TreeOntology

**Comment by vddesai1871** [comment]
Hey, @pietercolpaert thanks for these examples.
> this has a property lc:departureTimeQuery: it means it’s going to redirect to a page in an ordered page collection that contains the timestamp given.

Can you explain why you've defined  `lc:departureTimeQuery`, can't we use `lc:departureTime` instead of this. Both have DateTime as the range.

**Comment by pietercolpaert** [comment]
The semantics of the property are also relevant with regards to how to interpret the search form. Maybe you are looking for something that does *not* contain this thing: how would you describe that then? I would just introduce something like `lc:doesNotContainDepartureTimeQuery`. Thus, I think we should be able to have a more precise URI containing the exact semantics of what the expected outcome is of filling out this property.

We could try to even go further, and describe something like lc:departureTimeQuery or hydra:freetextQuery using SHACL, but I believe that would lead us too far into automation: just hard-coding clients to recognize particular search forms is already nice enough for now.

**Comment by Mec-iS** [comment]
Thanks Pieter for joining the conversation.
Just a link to this one that may be relevant for the subject: https://github.com/HTTP-APIs/hydrus/issues/302
